# This workflow builds the Xamarin.Forms iOS-only project

name: Xamarin.Forms iOS only

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Set Xcode version to use
      run: |
        XCODE_ROOT=/Applications/Xcode_15.3.app
        sudo xcode-select -s $XCODE_ROOT

    - name: "Display Xcode current version"
      run: xcode-select -p

    - name: Install Xamarin SDKs
      run: |
        brew install --cask xamarin-ios

    - name: Build iOS app
      run: >
        msbuild src/XamarinFormsIosApp/XamarinFormsIosApp.iOS/XamarinFormsIosApp.iOS.csproj
        /p:Configuration=Release
        /p:Platform=iPhone
        /p:IsMacEnabled=false
        /p:BuildIpa=false
        /t:Restore
        /t:Build
