# This workflow builds the Xamarin.Forms iOS-only project

name: Xamarin.Forms iOS only

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Set Xcode version to use
      run: |
        XCODE_ROOT=/Applications/Xcode_16.2.app
        echo "MD_APPLE_SDK_ROOT=$XCODE_ROOT" >> $GITHUB_ENV
        sudo xcode-select -s $XCODE_ROOT

    - name: "Display Xcode current version"
      run: xcode-select -p

    - name: Install Mono Framework MDK
      run: |
        wget --no-verbose https://download.mono-project.com/archive/6.12.0/macos-10-universal/MonoFramework-MDK-6.12.0.188.macos10.xamarin.universal.pkg
        sudo chmod +x MonoFramework-MDK-6.12.0.188.macos10.xamarin.universal.pkg
        sudo installer -pkg MonoFramework-MDK-6.12.0.188.macos10.xamarin.universal.pkg -target /

    - name: "Display mono and msbuild current versions"
      run: |
        mono --version
        msbuild --version

    - name: Install Xamarin SDKs
      run: |
        brew install --cask xamarin-ios

    - name: Build iOS app
      run: >
        msbuild src/XamarinFormsIosApp/XamarinFormsIosApp.iOS/XamarinFormsIosApp.iOS.csproj
        /p:Configuration=Release
        /p:Platform=iPhone
        /p:IsMacEnabled=false
        /p:BuildIpa=false
        /t:Restore
        /t:Build
